### ISSUE TITLE
AMQ_ENABLE_METRICS_PLUGIN = true makes container fail to start

### ISSUE THREAD

**Issue by alainpham** [arkmq-org/activemq-artemis-broker-kubernetes-image#35]
By enabling the metrics plugin the container fails to start. with environment variable AMQ_ENABLE_METRICS_PLUGIN: "true" to run the container

```
Caused by: java.lang.ClassNotFoundException: org.apache.activemq.artemis.core.server.metrics.plugins.ArtemisPrometheusMetricsPlugin
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at org.apache.activemq.artemis.utils.ClassloadingUtil.newInstanceFromClassLoader(ClassloadingUtil.java:55)
```

it seems like
-   metrics.war is not present in /opt/amq/web 
-  artemis-prometheus-metrics-plugin is not present in /opt/amq/lib

**Comment by gaohoward** [comment]
The standard broker image doesn't ship with those artifacts and the operator doesn't handle it for the moment. I think the workaround is to use init-container to manually add those missing artifacts. Here are some init container examples:

https://github.com/artemiscloud/artemiscloud-examples/tree/main/operator/init

**Comment by alainpham** [comment]
Ok thanks for the feedback.
I created a custom image with a dockerfile and managed to get it working.

https://github.com/alainpham/activemq-artemis-kubernetes-with-metrics/blob/master/docker/Dockerfile

**Comment by brusdev** [comment]
The artemis-prometheus-metrics-plugin is included in the broker kubernetes image since activemq-artemis-broker-kubernetes-image v1.0.11, see https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/pull/46
