### ISSUE TITLE
Error enabling the jolokia agent with CONFIG_BROKER disabled

### ISSUE THREAD

**Issue by brusdev** [arkmq-org/activemq-artemis-broker-kubernetes-image#38]
Describe the bug
Enabling the AMQ_ENABLE_JOLOKIA_AGENT environment variable and disabling the CONFIG_BROKER environment variable, the broker container prints the following error:
```
Could not start Jolokia agent: java.lang.IllegalStateException: Cannot open keystore for https communication: 
Exception FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f14179a8e91, pid=1, tid=26
#
# JRE version: OpenJDK Runtime Environment 21.9 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM 21.9 (17.0.3+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x21e91]  abort+0x203
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /home/jboss/core.1)
#
# An error report file with more information is saved as:
# /home/jboss/hs_err_pid1.log
in thread "main" java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.IllegalArgumentException: jolokia: Can not find configuration file /opt/jboss/container/jolokia/etc/jolokia.properties
    at org.jolokia.jvmagent.JvmAgentConfig.readConfig(JvmAgentConfig.java:127)
    at org.jolokia.jvmagent.JvmAgentConfig.getDefaultConfig(JvmAgentConfig.java:97)
    at org.jolokia.jvmagent.JolokiaServerConfig.init(JolokiaServerConfig.java:103)
    at org.jolokia.jvmagent.JvmAgentConfig.init(JvmAgentConfig.java:61)
    at org.jolokia.jvmagent.JolokiaServerConfig.<init>(JolokiaServerConfig.java:94)
    at org.jolokia.jvmagent.JvmAgentConfig.<init>(JvmAgentConfig.java:55)
    at org.jolokia.jvmagent.JvmAgentConfig.<init>(JvmAgentConfig.java:46)
    at org.jolokia.jvmagent.JvmAgent.premain(JvmAgent.java:72)
    ... 6 more
Caused by: java.io.FileNotFoundException: /opt/jboss/container/jolokia/etc/jolokia.properties (No such file or directory)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
    at org.jolokia.jvmagent.JvmAgentConfig.readConfig(JvmAgentConfig.java:124)
    ... 13 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

```
To Reproduce
docker run --name artemis --env AMQ_USER=admin --env AMQ_PASSWORD=admin --env AMQ_ENABLE_JOLOKIA_AGENT=true -e CONFIG_BROKER=false -e CONFIG_INSTANCE_DIR=... artemiscloud/activemq-artemis-broker-kubernetes:1.0.6

**Comment by brusdev** [comment]
Fixed in quay.io/artemiscloud/activemq-artemis-broker-kubernetes/1.0.7
